Loop

In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])

for i in np.nditer(arr):
    print(i,end=" ")

1 2 3 4 5 6 

In [4]:
for i,j in np.ndenumerate(arr):
    print(i,j,end=" ")

(0,) 1 (1,) 2 (2,) 3 (3,) 4 (4,) 5 (5,) 6 

views vs copies

In [5]:
view = arr[:2]
view[0] = 100
print(arr)

[100   2   3   4   5   6]


In [6]:
copies = arr.copy()
copies[0] = 200
print(arr)

[100   2   3   4   5   6]


Transpose

In [7]:
arr = np.array([[1, 2, 3, 4, 5],[1,2,3,4,5]])
arr.transpose() 

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])