Indexing

In [2]:
import numpy as np

In [13]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 8, 9], [10, 11, 12, 13, 14]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 8]])

In [15]:
arr[1:, :2]

array([[ 6,  7],
       [10, 11]])

Concatenation

In [3]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([7, 8, 9, 10, 11, 12])
arr3 = np.concatenate((arr1, arr2))
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Vstack vs Hstack

In [ ]:
varr = np.vstack((arr1, arr2))
varr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
harr = np.hstack((arr1, arr2))
harr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
arr = np.stack((arr1, arr2), axis=1)
arr

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [8]:
arr = np.stack((arr1, arr2), axis=0)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])