Indexing

In [6]:
import numpy as np

In [13]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 8, 9], [10, 11, 12, 13, 14]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 8]])

In [15]:
arr[1:, :2]

array([[ 6,  7],
       [10, 11]])