1. speed(Python vs Numpy)

In [4]:
import numpy as np
import time

def Python_speed(arr):
    start_time = time.time()
    for i in range(len(arr)):
        arr[i] = arr[i] * 2
    end_time = time.time()
    return abs(end_time - start_time)

def Numpy_speed(arr):
    start_time = time.time()
    arr = arr * 2
    end_time = time.time()
    return abs(end_time - start_time)

if __name__ == "__main__":
    arr = [1,2,3,4,5,7]
    print("Python speed: ", Python_speed(arr))
    print("Numpy speed: ", Numpy_speed(np.array(arr)))

Python speed:  3.337860107421875e-06
Numpy speed:  2.1457672119140625e-05


2. Memory Management

In [6]:
import sys
a = [1,2,3,4,5,6,7,6]
arr = np.array(a)
print("list memory in terms of bytes:",sys.getsizeof(a))
print("array memory in terms of bytes:",sys.getsizeof(arr))

list memory in terms of bytes: 120
array memory in terms of bytes: 176


Dimensions vs shapes

In [24]:
arr = np.array(6)
print(arr.ndim) ## 0D array
arr = np.array([1,2,3,4,4])
print(arr.ndim)  ## 1D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)  ## 2D array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)  ## 3D array

arr = np.array(6)
print(arr.shape) 
arr = np.array([1,2,3,4,4])
print(arr.shape)
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)  
arr = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]
            ])
print(arr.shape) 

0
1
2
3
()
(5,)
(2, 3)
(2, 2, 3)


Range Function

In [14]:
arr = np.arange(1,10,2) ## start, stop, step
print(arr)
arr = np.arange(-1,-10,-2)
print(arr) 

[1 3 5 7 9]
[-1 -3 -5 -7 -9]


Linspace Function

In [16]:
arr = np.linspace(1,10,5) ## start, stop, number of elements
print(arr)
print(arr[0])

[ 1.    3.25  5.5   7.75 10.  ]
1.0


Logspace Function

In [18]:
arr = np.logspace(1,3,5) ## start, stop, number of elements
print(arr)

[  10.           31.6227766   100.          316.22776602 1000.        ]


Zeros Function and Ones Function

In [25]:
arr = np.zeros(5)
print(arr)
arr = np.zeros([2,3])
print(arr)

arr = np.ones(5)
print(arr)
arr = np.ones([2,3])
print(arr)
arr= np.ones([2,3],dtype=int)
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


Full Function

In [26]:
arr = np.full(10,5)
print(arr)
arr = np.full([2,3],5)
print(arr)
arr = np.full([2,3],5,dtype=int)
print(arr)


[5 5 5 5 5 5 5 5 5 5]
[[5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]]


Empty Function

In [29]:
arr = np.empty(100) ## uninitialized array
print(arr)

[4.94065646e-324 6.95177464e-310 3.73513628e-321             nan
 4.94065646e-322 1.15998412e-028 6.80275364e+199 1.93307993e+261
 6.21066040e+175 6.32677658e+180 8.61177748e-072 2.88854907e+214
 2.04803851e+161 1.94920553e-153 7.96346116e+159 4.09834249e+199
 8.17157985e-130 1.04918616e-153 6.34399954e+151 1.04917707e-153
 2.59027913e-144 7.96346116e+159 2.59027921e-144 7.96346116e+159
 5.98973426e+247 4.65267158e+199 1.35499401e+248 7.96346116e+159
 2.59027905e-144 3.28710422e+161 9.28485452e+159 7.28395912e-143
 7.75444640e+228 1.04917707e-153 2.73243930e+161 1.10491095e+267
 2.59042262e-144 2.03890423e+180 1.18086616e-095 1.67772392e+243
 1.16466606e-028 3.77778425e+180 1.15998412e-028 9.11738623e+276
 4.27255699e+180 8.80088569e+199 1.16267760e-028 9.31115231e+242
 1.05235777e-153 1.56261167e-033 1.11789342e+253 1.04917578e-153
 1.94918964e-153 1.23755530e+214 1.41739410e+190 1.16096835e-028
 1.39028129e-142 1.94920672e-153 6.01409632e+175 2.59033485e-144
 2.59903832e-144 2.595497

Random Function

In [33]:
arr = np.random.randint(1,100,10)
print(arr)
arr = np.random.rand(10) 
print(arr)

arr = np.random.randn(10) ### standard normal distribution mean = 0, std = 1
print(arr)
arr = np.random.randint(1,10,size=(2,5)) ### standard normal distribution mean = 0, std = 1
print(arr)

[20 95 80 25 68 79 41 86 37 57]
[0.44095521 0.70231096 0.73457228 0.36821146 0.47565694 0.25008093
 0.64428127 0.07113279 0.65110432 0.59206499]
[-1.34683157  0.28707109 -0.55717981  0.78389199 -0.76558207 -0.15543316
 -0.92090094 -0.58780852  0.21426329  0.45349313]
[[8 5 7 5 2]
 [5 7 3 2 7]]
