Reshaping

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)
arr.reshape(6,1)

array([1, 2, 3, 4, 5, 6])

Ravel

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)
arr.reshape(6,1)
arr.ravel() ## convert the multi dimensional array into single dimensional array

array([1, 2, 3, 4, 5, 6])

Flatten

In [ ]:
### flatten is also used to convert multi dimensional array into single dimensional array 
### but it will return the copy of original array where as ravel will return the view of original array.
arr = np.array([1,2,3,4,5,6])
t = arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
t.flatten()
# t

array([1, 2, 3, 4, 5, 6])

Arithmetic operations

In [16]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])
print(arr1 + arr2) ### element wise addition
print(arr1 - arr2) ### element wise subtraction
print(arr1 * arr2) ### element wise multiplication
print(arr1 / arr2) ### element wise division
print(arr1 // arr2) ### element wise floor division
print(arr1 % arr2) ### element wise modulus


[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
[0 0 0 0 0 0]
[1 2 3 4 5 6]


Universal Function ---> ufuncs

In [17]:
arr = np.array([1,4,9,16])
np.sqrt(arr) 

array([1., 2., 3., 4.])